// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvq3vWY-8zo6Oy_pH7qioWNDXJZbeh-Ic',
    appId: '1:648437378605:android:ed01be4d024421e62e92a4',
    messagingSenderId: '648437378605',
    projectId: 'worktracker-1e0fa',
    storageBucket: 'worktracker-1e0fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4RZiJHrC3O8hZ3lq64R7oy3lrFw9xT44',
    appId: '1:648437378605:ios:e9e3e1dcdec9e6162e92a4',
    messagingSenderId: '648437378605',
    projectId: 'worktracker-1e0fa',
    storageBucket: 'worktracker-1e0fa.appspot.com',
    androidClientId: '648437378605-u714be8g2mltkgultejcdc277jr6u693.apps.googleusercontent.com',
    iosClientId: '648437378605-rd378nr4c6gbhct6vldb3dr2frb9ihom.apps.googleusercontent.com',
    iosBundleId: 'com.example.workTracker',
  );
}
